### ISSUE TITLE
Meeting 12-12 issues

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/finjector#196]
- [x] #216
- [x] #217
- [ ] Nice to have: add status toast for all status changes in app
- [x] #205
- [x] #210
- [x] #211
- [x] #223
- [x] Change language on entry GL/PPM toggle (says COA)
- [x] #202
- [x] #227
- [x] #197
- [x] Move new+ buttons on homepage
- [x] #219
- [x] Activate and disabled states of finjector button
- [x] #229
- [x] #234
- [x] Entry -- save and use button should be 2 different buttons. Save takes to details. (Maybe this isn't needed now? It changes based on if it is in the popup or now (the new entry page vs. the edit)
- [x] #209
- [x] #231
- [x] #208
- [x] Remove remove button from entry page if you don't have edit access. Also hide duplicate (JCS- I think we always want duplicate? Hide Save if you don't have edit access?)
- [ ] #267
- [x] Indent folder names on landing

TEAMS
- [x] Order by personal first and then team name on both entry and team
- [x] In user management modal, change to email / kerb
- [x] Hide view team admins on personal team
- [x] Sort folders by name
- [x] Remove manage users on team and folders
- [x] #198
- [x] Remove view team admins if you are admin
- [x] Create should be first in folder and just say Create new chart string
- [x] Order buttons by everyone can view first, admins after
- [x] Add leave folder button/option, only if you have folder permissions

BREADCRUMBS
- [x] Crumb regions should be static and contain team and folder info whenever needed
- [x] ex crumbs: home / team / folder / chart string detail
- [x] ex: /team/12/folder/23/details/chart/13/3110-69882-ADNO001-480000-00-000-0000000000-000000-0000-000000-000000

**Comment by laholstege** [comment]
things we discussed: 
- [ ] do we want to always load all the JS on popup? 
- [ ] buttons not aligned in popup 
- [ ] popup styles on details, 2nd col collides with 3rd 
- [ ] info text on share popup on what sharing means in modal
- [ ] hover copy button sticking on details page when you hover over popup text 
- [ ] ability to reassign roles instead of removing and adding
