### ISSUE TITLE
Add title text to buttons

### ISSUE THREAD

**Issue by cydoval** [ucdavis/finjector#209]

**Comment by cydoval** [comment]
<img width="1165" alt="Screenshot 2023-12-13 at 11 55 45 AM" src="https://github.com/ucdavis/finjector/assets/1899553/2724e331-f3f6-43b7-8fee-2f0b4a8e3e82">
do we only want titles for these buttons on entry? 
what should they say?

**Comment by srkirkland** [comment]
just for icons.  looks good
