### ISSUE TITLE
Popup to allow selection of Team or Folder

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/finjector#263]
New streamlined pages for selecting a team or folder for use in importing COAs to other apps in bulk (augmenting single COA selection we have now).  So I'm thinking:

1. New popup-friendly page to search through your teams
2. click on a team and then either "USE" it or look through folders
3. if you pick a folder, the only option is to use it.
4. Once selected, we'd go to the db and get all COAs attached to that team/folder that the user can see.
5. Send that back to the calling app as an array of COAs (name & chart string)

Also we'd need a new `window.Finjector.findChartSegmentString` popup method which clients can call.  It'd do almost the exact same thing but call a different url by default to show the new UI.

**Comment by cydoval** [comment]
<img width="858" alt="Screenshot 2024-01-12 at 10 57 40 AM" src="https://github.com/ucdavis/finjector/assets/1899553/4f28a722-bd02-419f-b71e-6a3a83bfe44c">
https://github.com/ucdavis/finjector/pull/266
