### ISSUE TITLE
Keep cosmos db connection warm

### ISSUE THREAD

**Issue by sprucely** [ucdavis/finjector#57]
Need to figure out how to keep the connection warm without wasting too many request units.

**Comment by sprucely** [comment]
One option to look at:
`Configure the ConnectionPolicy.IdleConnectionTimeout property must be greater than or equal to 10 minutes. The recommended values are between 20 minutes and 24 hours.`

**Comment by srkirkland** [comment]
not needed, dumping cosmo for SQL
