### ISSUE TITLE
Details page

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/finjector#70]
Have a details page, probably accessed by a new icon/button next to the edit - use on the main list.

This would show GL approvers (maybe group by type) and Project managers for PPM

Also, can show other info like what we have in opp:
And any warnings
https://github.com/ucdavis/Purchasing/blob/AggieEnterprise/Purchasing.Core/Services/AggieEnterpriseService.cs#L73

**Comment by jSylvestre** [comment]
Maybe for PPM we should show the GL posting info?
query ppmTaskByProjectNumberAndTaskNumber($projectNumber: PpmProjectNumber!, $taskNumber: PpmTaskNumber!) {
  ppmTaskByProjectNumberAndTaskNumber(projectNumber: $projectNumber, taskNumber: $taskNumber) {
    taskNumber
    name
    billable
    chargeable
    eligibleForUse
    glPostingProgramCode
    glPostingPurposeCode
    glPostingFundCode
    glPostingActivityCode
  }
}

**Comment by jSylvestre** [comment]
Some wish list info from Brian
Jason Sylvestre
:killitwithfire:  [1:54 PM](https://ucdavis.slack.com/archives/DBPHBBELC/p1694724851887089)
Is it just the GL posting for PPM you need?
And the desc of the segments?
There are probably some other things we could add, but if you have a wish list earlier that might make it easier.
Also, the details would only be for one that is saved I think. At least for now.


Brian McEligot
  [1:57 PM](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725073342469)
Yes, details only for one that is saved/stored.
[1:59](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725141767649)
OK, if we went the display field route, like we are doing now with Award and Funding Source, the display fields needed would be:
Entity
Fund
Purpose
Program
Activity
[2:01](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725270833469)
If we went the route of creating a full UC Path format chartstring that is display only, the format would be:
Entity-Fund-FinancialDept-Purpose-Program-Project-Activity-Task-Award
Noting that Project and Task come from the user-entered and saved POET string, and possibly Financial Dept from the Org/Dept entered in the POET string.


Jason Sylvestre
:killitwithfire:  [2:02 PM](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725328525379)
The image you showed had the rollup dept. Might be able to get that, but if you don't need it I'd avoid it.


Brian McEligot
  [2:02 PM](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725361503609)
Nope, that is derived (non-enterable) in the UC Path UI, so I don't think we would need to grab it.
New
[2:04](https://ucdavis.slack.com/archives/DBPHBBELC/p1694725491289419)
On the wish list of things that I would like to see included on a details page:
PPM roles:
Project Manager name, email address, and maybe even department affiliation (via IAM?)
Principal Investigator name, email address, dept affiliation
Other PPM info:
Project/Task Start Date
Project/Task End Date
GL Info:
SCM Financial Department approvers, name, email, dept affiliation

**Comment by jSylvestre** [comment]
The second one should have GL posting values in UAT
Sponsored PPM project: K30V625323-TASK01-VHFS001-522201
Non-Sponsored PPM project: FPAPLS1819-COFAES-APLS002-522201

**Comment by sprucely** [comment]
Just a note; to get GL posting info for PPM COAs...
https://github.com/ucdavis/AggieEnterpriseApi/blob/main/src/AggieEnterpriseApi/Queries/ppmTaskByProjectNumberAndTaskNumber.graphql

**Comment by jSylvestre** [comment]
On the list page, add INFO with this icon between Edit and Use
faLightbulb

**Comment by jSylvestre** [comment]
@sprucely FYI, the GL and PPM validate chart strings should get all/most of the details you need.

**Comment by jSylvestre** [comment]
In addition to the details, we should list the Financial Officers for the Dept/Org.
https://github.com/ucdavis/AggieEnterpriseApi/pull/78/files#diff-daaa3b5fcbb6b57d5f0ac757c0051d6a4e70d1804d3ee8a111aa05d7ed4784c6R64
