### ISSUE TITLE
Folder/groups

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/finjector#78]
Brian McEligot

I was discussing Finjector with a group of fiscal officers last week, and they had an interesting suggestion.  I don't think it is urgent, doesn't need to be explored before AE go live (and I'd prioritize advanced sharing first), but wanted to pass it along in the form of a "user story" so we can keep it in mind if feasible for a future update.

As a frequent user of Finjector and someone who manages hundreds of COA chartstrings in my job as Fiscal Officer, I'd like to have the option to group and organize my favorites into folders or groupings based on the unit/center/institute that uses those chartstrings most commonly.  I'd like to be able to nickname the folders/groups.

**Comment by srkirkland** [comment]
New - team and folder structure that can be shared and edited collaboratively.  move DB to SQL.  create script for one-time migration.

* Team -- Anyone can create a team and they are owner/admin.  They can add users in roles Collaborator and Reviewer.  
* Folder -- a Team can have 1+ folders.  Each folder can have users in Collaborate and Reviewer.
* Folder COA -- each folder can have a list of COAs, and anyone with collab or higher on the folder OR team can CRUD them.
* On finjector homepage, you see every COA you have access to in your teams & folders somehow (cal figure out the details).
* Ability to leave a team/folder at any time (if you are owner, you must delete or transfer)
* When creating a COA if it isn't part of a team, each person should have their own personal team with a folder called "Personal" that things go into by default
* Ability to do single share -- just share out a COA which opens the details page. COA doesn't need to be save/no link to origin.
* Ability to view my folders/teams and choose to leave at any time.  
* Can add permissions to folders/teams at your level and below.

**Comment by srkirkland** [comment]
https://ucdavis.slack.com/archives/G011R5HQ4DR/p1699398405083759

**Comment by cydoval** [comment]
https://www.sketch.com/s/802165df-99f0-49a9-93b0-077997ed1de9

**Comment by srkirkland** [comment]
feature completed
